### ISSUE TITLE
Broken after 2020.1 

### ISSUE THREAD

**Issue by matt-fisher** [gantsign/ansible-role-intellij#255]
Looks like the locations/structure of the various config files/directories has changed in 2020.1. This role still installs without error but none of the configurations take affect. Happy to create some PRs that fix the bits I understand.

Here's the link to the new config locations
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519

**Comment by freemanjp** [comment]
@matt-fisher thanks for reporting this issue. You can find the fix in the [6.0.0](https://github.com/gantsign/ansible-role-intellij/releases/tag/6.0.0) release of this role.
