### ISSUE TITLE
Replace apt module with package

### ISSUE THREAD

**Issue by wyvern8** [gantsign/ansible-role-intellij#70]
Hi, any chance you could use the 'package' module rather than 'apt'?  Even though not documented as supported, ive been using your role in centos7 vm bakes, and the newer versions can no longer install.

**Comment by freemanjp** [comment]
@wyvern8: thanks for the feedback, CentOS 7 is now working & supported as of version 2.8.0.

**Comment by wyvern8** [comment]
Thanks for this.  I've run a packer bake using the updated  role and the task all completed now.  Will do some testing of the vm next week.

**Comment by wyvern8** [comment]
i've tested this over the last few days and all looks good! thanks again.

**Comment by freemanjp** [comment]
Great, thanks for letting me know.
