### ISSUE TITLE
Add support for installing plugins from channels

### ISSUE THREAD

**Issue by ripla** [gantsign/ansible-role-intellij#93]
JetBrains plugin repository allows uploading plugins to specific channels. Usual channels are Stable, EAP, Nightly etc. The default is the stable channel. It is possible to modify the download script to use the channel information by adding e.g. `&channel=EAP` to the download URL here https://github.com/gantsign/ansible-role-intellij/blob/6d52f5797881582717a820a4e83ca89bfe32b238/templates/install-intellij-plugins.sh.j2#L23

**Comment by freemanjp** [comment]
@ripla, thanks for the feedback.

I've made the plugin manager URL configurable, which you can use to specify the channel.

I considered adding a dedicated channel variable, but I decided not to, because I don't want the overhead of officially maintaining support for EAP versions.
